-- Supabase/Postgres schema compatibility patch for chess-match-selector
-- Safe to run multiple times.

ALTER TABLE IF EXISTS students
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE IF EXISTS rounds
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'open';
ALTER TABLE IF EXISTS rounds
  ADD COLUMN IF NOT EXISTS homework_total_questions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS rounds
  ADD COLUMN IF NOT EXISTS missing_homework_policy VARCHAR(20) NOT NULL DEFAULT 'zero';
ALTER TABLE IF EXISTS rounds
  ADD COLUMN IF NOT EXISTS homework_metric_mode VARCHAR(20) NOT NULL DEFAULT 'pct_correct';
ALTER TABLE IF EXISTS rounds
  ADD COLUMN IF NOT EXISTS completion_override_reason TEXT NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS notation_submitted_white BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS notation_submitted_black BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS attendance
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'present';

ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS white_correct INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS white_incorrect INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS black_correct INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS black_incorrect INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS white_submitted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS black_submitted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS white_pct_wrong DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS black_pct_wrong DOUBLE PRECISION NOT NULL DEFAULT 0.0;

CREATE TABLE IF NOT EXISTS audit_logs (
  id SERIAL PRIMARY KEY,
  classroom_id INTEGER NOT NULL,
  round_id INTEGER NOT NULL,
  match_id INTEGER NOT NULL,
  actor_teacher_id INTEGER NOT NULL,
  field_name VARCHAR(100) NOT NULL,
  old_value TEXT NOT NULL DEFAULT '',
  new_value TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS audit_logs
  ADD COLUMN IF NOT EXISTS actor_teacher_id INTEGER;
ALTER TABLE IF EXISTS audit_logs
  ADD COLUMN IF NOT EXISTS field_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS audit_logs
  ADD COLUMN IF NOT EXISTS old_value TEXT NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS audit_logs
  ADD COLUMN IF NOT EXISTS new_value TEXT NOT NULL DEFAULT '';

-- Drop FK constraints that may have been added by create_all().
-- Audit logs should be a standalone table without cascading dependencies.
ALTER TABLE IF EXISTS audit_logs DROP CONSTRAINT IF EXISTS audit_logs_classroom_id_fkey;
ALTER TABLE IF EXISTS audit_logs DROP CONSTRAINT IF EXISTS audit_logs_round_id_fkey;
ALTER TABLE IF EXISTS audit_logs DROP CONSTRAINT IF EXISTS audit_logs_match_id_fkey;
ALTER TABLE IF EXISTS audit_logs DROP CONSTRAINT IF EXISTS audit_logs_actor_teacher_id_fkey;
