-- Supabase/Postgres schema compatibility patch for chess-match-selector
-- Safe to run multiple times.

ALTER TABLE IF EXISTS students
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE IF EXISTS rounds
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'open';

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS attendance
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'present';

ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS white_correct INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS white_incorrect INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS black_correct INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS homework_entries
  ADD COLUMN IF NOT EXISTS black_incorrect INTEGER NOT NULL DEFAULT 0;
